services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Expone el puerto del frontend
    volumes:
      - /app/venv
    command: sh -c "yarn build && yarn start"

    depends_on:
      - backend
